# Generated by Django 4.2.10 on 2024-02-17 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inmobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                (
                    "type_item",
                    models.CharField(
                        choices=[
                            ("APARTAMENTO", "APARATMAENTO"),
                            ("KITNET", "KITNET"),
                            ("CASA", "CASA"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_locate", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Imóvel",
                "verbose_name_plural": "imóveis",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RegisterLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_start", models.DateTimeField(verbose_name="Início")),
                ("dt_end", models.DateTimeField(verbose_name="Fim")),
                (
                    "create_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.cliente"
                    ),
                ),
                (
                    "inmobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reg_locacao",
                        to="myapp.inmobile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrar Locação",
                "verbose_name_plural": "Registrar Locação",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="InmobileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images", verbose_name="Images")),
                (
                    "inmobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inmobile_images",
                        to="myapp.inmobile",
                    ),
                ),
            ],
        ),
    ]
